### ISSUE TITLE
clamd reporting "no such file or directory" for files in subdirectories

### ISSUE THREAD

**Issue by tinnyb** [fumiyas/samba-virusfilter#26]
Compiled samba-4.4.15 with samba-virusfilter support.  Configured for clamd support.  It appears for me that files in the root of a share are correctly passed to clamd for assessment, but files in subdirectories of a given share have their intermediate path stripped before being passed to clamd, which reports that there is no such file.  Ref attached log extracts from "/usr/local/samba/sbin/smbd -i -d8 -S" session.

**Log example where scan completes for file present and opened in the root of the share**
[correct_root_file_scan.txt](https://github.com/fumiyas/samba-virusfilter/files/1189012/correct_root_file_scan.txt)

**Log example where scan fails for file which is located in a subdirectory "dir"; note "check_reduced_name" != "scanning file"**
[faulty_subdir_file_scan_error.txt](https://github.com/fumiyas/samba-virusfilter/files/1189013/faulty_subdir_file_scan_error.txt)

**Comment by galitus** [comment]
Hey,

i get the same error on gentoo with samba 4.5.10 and self-compiled virusfilter version from your github master branch. The subdirectory folderpath is just stripped away, so that clamav is not finding the file.

Is this version maybe broken? Do i have to use the release version 0.1.4 (i just noticed, it is just for samba 3.6.)?

Help and a fix would be much appreciated.

Thanks in advance

**Comment by fumiyas** [comment]
Please retry with the latest Samba release and  bundled `vfs_virusfilter`(8) module, and report issue to upstream if you see a problem.
